name: Job Output workflow
on: push
jobs:
  push_job:
    runs-on: ubuntu-latest
    outputs:  # This section defines the outputs of the job
      script_file: ${{ steps.publish.outputs.script_file }} # This output captures the script file names from the publish step
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci   

      - name: Build project
        run: npm run build   

      - name: Publish JS FilesName
        id: publish # This step publishes the JS files and captures their names # This step is identified by the id 'publish' for later reference
        run: find dist/assets/*.js -type f -execdir echo 'script_file={}' >> $GITHUB_OUTPOT ';' # This command finds all JS files in the dist/assets directory and prints their names
        # This is useful for debugging to ensure the build process has created the expected files
        # It can be removed or modified as needed in production workflows
        # This step is optional and can be customized based on the project's requirements


      - name : Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
             build/
             dist/
             public/
             package.json
          
  deploy_job:
    runs-on: ubuntu-latest
    needs: push_job 
    steps:
      - name: Download artifact 
        uses: actions/download-artifact@v4 
        with:
          name: build-artifact 
      - name: Output content
        run: ls      
      - name: Output FilesName
        run: echo "${{ needs.push_job.outputs.script_file }}" # This command outputs the script file names captured from the previous job
        
      - name: Deploy application 
        run: echo "Deploying application..."